package instructorFrontEnd;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MAYAR
 */



import database.JsonUserDatabase;
import models.Instructor;
import models.User;
import models.Course;

import Services.CourseManager;
import Services.LessonManager;
import frontEnd.Login;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.UUID;
import java.util.ArrayList;
import java.util.List;


public class InstructorDashboardFrame1 extends javax.swing.JFrame {
 private CourseManager courseManager = new CourseManager();
    private LessonManager lessonManager = new LessonManager();

    // UI model + state
    private DefaultListModel<String> courseModel;
    private List<String> courseIds = new ArrayList<>();
    private JsonUserDatabase jsonUserDb;
    private Instructor currentInstructor;

    /**
     * Creates new form InstructorDashboardFrame
     */
    public InstructorDashboardFrame1() {
      initComponents();

    
     
        courseModel = new DefaultListModel<>();
        jListCourses.setModel(courseModel);
        jListCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        
        jsonUserDb = new JsonUserDatabase();

        
        loadOrCreateInstructor();

        if (currentInstructor != null && currentInstructor.getCreatedCourses() != null) {
            for (String cid : currentInstructor.getCreatedCourses()) {
                courseIds.add(cid);
                courseModel.addElement("(course " + cid + ")"); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListCourses = new javax.swing.JList<>();
        btnCreate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnManageLessons = new javax.swing.JButton();
        btnViewEnrolled = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnInsights = new javax.swing.JButton();
        pnlInsightsSummary = new javax.swing.JPanel();
        lblEnrolled = new javax.swing.JLabel();
        lblAvgScore = new javax.swing.JLabel();
        lblCompletion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListCourses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCourses);

        btnCreate.setText("Create course");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit courses");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnManageLessons.setText("Manage");
        btnManageLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLessonsActionPerformed(evt);
            }
        });

        btnViewEnrolled.setText("View enrolled");
        btnViewEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEnrolledActionPerformed(evt);
            }
        });

        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnInsights.setText("insights");
        btnInsights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsightsActionPerformed(evt);
            }
        });

        pnlInsightsSummary.setVerifyInputWhenFocusTarget(false);

        lblEnrolled.setText("Enrolled");

        lblAvgScore.setText("average");

        lblCompletion.setText("completion");

        javax.swing.GroupLayout pnlInsightsSummaryLayout = new javax.swing.GroupLayout(pnlInsightsSummary);
        pnlInsightsSummary.setLayout(pnlInsightsSummaryLayout);
        pnlInsightsSummaryLayout.setHorizontalGroup(
            pnlInsightsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsightsSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnrolled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvgScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCompletion)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        pnlInsightsSummaryLayout.setVerticalGroup(
            pnlInsightsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsightsSummaryLayout.createSequentialGroup()
                .addGroup(pnlInsightsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnrolled)
                    .addComponent(lblAvgScore)
                    .addComponent(lblCompletion))
                .addGap(0, 211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCreate)
                                .addComponent(btnEdit))
                            .addComponent(btnDelete)
                            .addComponent(btnManageLessons)
                            .addComponent(btnViewEnrolled)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnInsights)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(pnlInsightsSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManageLessons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewEnrolled)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsights)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlInsightsSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int idx = jListCourses.getSelectedIndex();
    if (idx < 0) {
        JOptionPane.showMessageDialog(this, "Select a course first.", "No selection", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String currentTitle = courseModel.getElementAt(idx);
    NewJDialog dlg = new NewJDialog(this, true);
    dlg.setTitleField(currentTitle);
    dlg.setLocationRelativeTo(this);
    dlg.setVisible(true);
    if (!dlg.isSaved()) return;

    NewJDialog.CourseData data = dlg.getSavedCourse();

    // get backend id
    if (courseIds == null || idx >= courseIds.size()) {
        JOptionPane.showMessageDialog(this, "Course id missing; try refreshing the list.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String idStr = courseIds.get(idx);
    try {
        int courseId = Integer.parseInt(idStr);
        courseManager.updateCourse(courseId, data.getTitle(), data.getDescription() == null ? "" : data.getDescription());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid course id: " + idStr, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // update UI title immediately
    courseModel.set(idx, data.getTitle());
    jListCourses.setSelectedIndex(idx);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       // TODO add your handling code here:
        
   

    NewJDialog dlg = new NewJDialog(this, true);
    dlg.setLocationRelativeTo(this);
    dlg.setVisible(true);

    if (!dlg.isSaved()) return;
    NewJDialog.CourseData data = dlg.getSavedCourse();

    int instrNumeric = getInstructorNumericId();
    
    Course created = courseManager.createCourse(data.getTitle(),
                                               data.getDescription() == null ? "" : data.getDescription(),
                                               instrNumeric);
    if (created == null) {
        JOptionPane.showMessageDialog(this, "Failed to create course in backend.",
                                      "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    refreshCourseList();

    
    String idStr = String.valueOf(created.getCourseId());
    int idx = courseIds.indexOf(idStr);
    if (idx >= 0) jListCourses.setSelectedIndex(idx);

    JOptionPane.showMessageDialog(this,
        "Course created (id: " + created.getCourseId() + ")",
        "Created", JOptionPane.INFORMATION_MESSAGE);



       
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEnrolledActionPerformed
        // TODO add your handling code here:
          int idx = jListCourses.getSelectedIndex();
    if (idx < 0) {
        JOptionPane.showMessageDialog(this,
            "Please select a course first.",
            "No Course Selected",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    if (courseIds == null || idx >= courseIds.size()) {
        JOptionPane.showMessageDialog(this,
            "Course ID not available. Try refreshing the course list.",
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String idStr = courseIds.get(idx);
    try {
        int courseId = Integer.parseInt(idStr);
        //we are calling back end
        Course c = courseManager.getCourseById(courseId);
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                "Course not found in backend.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<Integer> students = c.getStudents();
        StringBuilder sb = new StringBuilder();
        if (students == null || students.isEmpty()) {
            sb.append("(none)");
        } else {
            for (Integer s : students) sb.append(s).append("\n");
        }

        JOptionPane.showMessageDialog(this,
            "Enrolled students for \"" + c.getTitle() + "\":\n" + sb.toString(),
            "Enrolled Students",
            JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "Invalid course id: " + idStr,
            "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // defensive: show an error if backend call fails
        JOptionPane.showMessageDialog(this,
            "Failed to load enrolled students:\n" + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnViewEnrolledActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int idx = jListCourses.getSelectedIndex();
    if (idx < 0) {
        JOptionPane.showMessageDialog(this, "Select a course first.", "No selection", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    int ok = JOptionPane.showConfirmDialog(this,
        "Delete selected course? This will remove it from backend and UI.",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
    if (ok != JOptionPane.YES_OPTION) return;

    // ensure mapping exists
    if (courseIds == null || idx >= courseIds.size()) {
        JOptionPane.showMessageDialog(this,
            "Course ID not available. Try refreshing the course list.",
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String idStr = courseIds.get(idx);
    try {
        int courseId = Integer.parseInt(idStr);
        // delete from backend
        courseManager.deleteCourse(courseId);
        
        refreshCourseList();
        JOptionPane.showMessageDialog(this,
            "Course deleted (id: " + courseId + ").",
            "Deleted", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "Invalid course id: " + idStr,
            "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Failed to delete course:\n" + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnManageLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLessonsActionPerformed
         int idx = jListCourses.getSelectedIndex();
    if (idx < 0) {
        JOptionPane.showMessageDialog(this, "Select a course first.", "No selection", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String selectedTitle = courseModel.getElementAt(idx);

    try {
        java.util.List<LessonManagerDialog.LessonData> initial = new java.util.ArrayList<>();
        // If you want to prefill with existing backend lessons, you could load them here.
        LessonManagerDialog dlg = new LessonManagerDialog(this, true, selectedTitle, initial);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        java.util.List<LessonManagerDialog.LessonData> lessons = dlg.getLessons();
        if (lessons != null && !lessons.isEmpty()) {
            
            if (courseIds == null || idx >= courseIds.size()) {
                JOptionPane.showMessageDialog(this, "Course id missing; refresh list.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String idStr = courseIds.get(idx);
            try {
                int courseId = Integer.parseInt(idStr);
                for (LessonManagerDialog.LessonData ld : lessons) {
                    String lt = ld.getTitle();
                    String lc = ld.getContent() == null ? "" : ld.getContent();
                    
                    lessonManager.addLesson(courseId, lt, lc);
                }
              
                if (this.getClass().getDeclaredMethods() != null) { 
                }
                try {
                    java.lang.reflect.Method m = this.getClass().getDeclaredMethod("refreshCourseList");
                    m.setAccessible(true);
                    m.invoke(this);
                } catch (NoSuchMethodException ignore) {
                    
                }
                JOptionPane.showMessageDialog(this,
                    "Saved " + lessons.size() + " lessons to backend for \"" + selectedTitle + "\".",
                    "Saved", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Invalid course id: " + idStr, "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                
                JOptionPane.showMessageDialog(this, "Error saving lessons: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            
        }
    } catch (NoClassDefFoundError | Exception e) {
        JOptionPane.showMessageDialog(this,
            "Lesson manager not available in this build.\nYou can still add lessons later via backend tools.",
            "Not Implemented", JOptionPane.INFORMATION_MESSAGE);
    
    }
    }//GEN-LAST:event_btnManageLessonsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Login l =new Login();
        l.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInsightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsightsActionPerformed
        // TODO add your handling code here:
        int idx = jListCourses.getSelectedIndex();
    if (idx < 0) {
        JOptionPane.showMessageDialog(this, "Select a course first.", "No selection", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    if (courseIds == null || idx >= courseIds.size()) {
        JOptionPane.showMessageDialog(this, "Course ID not available. Try refreshing the course list.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String idStr = courseIds.get(idx);
    int courseId;
    try {
        courseId = Integer.parseInt(idStr);
    } catch (NumberFormatException ex) {
        courseId = Math.abs(idStr.hashCode());
    }

    // Use local helpers (no external AnalyticsService required)
    java.util.Map<String, java.util.List<Number>> studentPerf = getStudentPerformanceMap();
    java.util.Map<String, Double> quizAvg = getQuizAveragesMap();
    java.util.Map<String, Double> completion = getCompletionPercentMap();

    // Update the small summary panel (enrolled, avg score, completion)
    try {
        Course c = courseManager.getCourseById(courseId);
        int enrolled = (c == null || c.getStudents() == null) ? 0 : c.getStudents().size();
        lblEnrolled.setText("Enrolled: " + enrolled);

        // overall average score from quizAvg map
        double overallAvg = 0;
        if (quizAvg != null && !quizAvg.isEmpty()) {
            overallAvg = quizAvg.values().stream().mapToDouble(Double::doubleValue).average().orElse(0.0);
        }
        lblAvgScore.setText(String.format("Avg Score: %.1f", overallAvg));

        // overall completion average
        double overallCompletion = 0;
        if (completion != null && !completion.isEmpty()) {
            overallCompletion = completion.values().stream().mapToDouble(Double::doubleValue).average().orElse(0.0);
        }
        lblCompletion.setText(String.format("Completion: %.1f%%", overallCompletion));
    } catch (Exception ignore) {
        // ignore if backend call fails and keep UI labels unchanged
    }

    // If all maps are empty, offer sample charts
    if ((studentPerf == null || studentPerf.isEmpty())
         && (quizAvg == null || quizAvg.isEmpty())
         && (completion == null || completion.isEmpty())) {
        int ok = JOptionPane.showConfirmDialog(this, "No analytics data available for this course. Show sample charts?", "No Data", JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION) return;
        ChartFrame f = ChartFrame.withSampleData();
        f.setVisible(true);
        return;
    }

    ChartFrame frame = new ChartFrame("Course Insights - " + (courseManager.getCourseById(courseId) == null ? idStr : courseManager.getCourseById(courseId).getTitle()),
                                      studentPerf, quizAvg, completion);
    frame.setVisible(true);
    }//GEN-LAST:event_btnInsightsActionPerformed
private void refreshCourseList() {
   
    if (courseModel == null) courseModel = new DefaultListModel<>();
    courseModel.clear();
    if (courseIds == null) courseIds = new ArrayList<>();
    courseIds.clear();

  
    int instrId;
    try {
        instrId = Integer.parseInt(currentInstructor.getUserId());
    } catch (Exception e) {
        instrId = Math.abs(currentInstructor.getUserId().hashCode());
    }

    List<Course> courses = courseManager.getCoursesByInstructor(instrId);
    if (courses == null) return;
    for (Course c : courses) {
        courseIds.add(String.valueOf(c.getCourseId()));
        courseModel.addElement(c.getTitle() == null ? "(no title)" : c.getTitle());
    }

    
    if (currentInstructor.getCreatedCourses() == null) currentInstructor.setCreatedCourses(new ArrayList<>());
    currentInstructor.getCreatedCourses().clear();
    currentInstructor.getCreatedCourses().addAll(courseIds);
    boolean ok = jsonUserDb.updateUser(currentInstructor.getUserId(), currentInstructor);
    if (!ok) jsonUserDb.addUserToFile(currentInstructor);

    
    jListCourses.setModel(courseModel);
}
    private int getInstructorNumericId() {
        if (currentInstructor == null || currentInstructor.getUserId() == null) return 0;
        String uid = currentInstructor.getUserId();
        try {
            return Integer.parseInt(uid);
        } catch (NumberFormatException ex) {
            return Math.abs(uid.hashCode());
        }
    }
    // Helper: studentName -> list of numeric scores
private java.util.Map<String, java.util.List<Number>> getStudentPerformanceMap() {
    java.util.Map<String, java.util.List<Number>> out = new java.util.LinkedHashMap<>();
    try {
        int instrNumeric = getInstructorNumericId();
        java.util.List<Course> courses = courseManager.getCoursesByInstructor(instrNumeric);
        if (courses != null && !courses.isEmpty()) {
            for (Course c : courses) {
                java.util.List<Integer> studs = c.getStudents();
                if (studs == null) continue;
                for (Integer sid : studs) {
                    String name = "Student " + sid;
                    out.putIfAbsent(name, new java.util.ArrayList<>());
                    // If you have student score data use it here. For now add placeholder values.
                    out.get(name).add((Number)(60 + (sid % 40)));
                }
            }
        }
    } catch (Exception e) {
        // ignore and fallthrough to sample data
    }

    if (out.isEmpty()) {
        out.put("Alice", java.util.Arrays.asList(80, 90, 85));
        out.put("Bob",   java.util.Arrays.asList(60, 70, 75));
    }
    return out;
}

// Helper: lesson title -> average quiz score
private java.util.Map<String, Double> getQuizAveragesMap() {
    java.util.Map<String, Double> out = new java.util.LinkedHashMap<>();
    try {
        int instrNumeric = getInstructorNumericId();
        java.util.List<Course> courses = courseManager.getCoursesByInstructor(instrNumeric);
        if (courses != null && !courses.isEmpty()) {
            // If LessonManager exposes real lesson/quiz data, replace this logic with that call.
            out.put("Lesson 1", 78.0);
            out.put("Lesson 2", 64.5);
            out.put("Lesson 3", 82.0);
            return out;
        }
    } catch (Exception e) {
        // fallthrough
    }
    out.put("Lesson 1", 78.0);
    out.put("Lesson 2", 64.5);
    out.put("Lesson 3", 82.0);
    return out;
}

// Helper: lesson title -> completion percent (0-100)
private java.util.Map<String, Double> getCompletionPercentMap() {
    java.util.Map<String, Double> out = new java.util.LinkedHashMap<>();
    try {
        // Replace with real logic if you track lesson completions in LessonManager or CourseManager.
        out.put("Lesson 1", 90.0);
        out.put("Lesson 2", 75.0);
        out.put("Lesson 3", 60.0);
        return out;
    } catch (Exception e) {
        // fallback to sample
    }
    out.put("Lesson 1", 90.0);
    out.put("Lesson 2", 75.0);
    out.put("Lesson 3", 60.0);
    return out;
}

 private void loadOrCreateInstructor() {
        List<User> users = jsonUserDb.readUsersFromFile();
        Instructor found = null;
        for (User u : users) {
            if (u instanceof Instructor) {
                found = (Instructor) u;
                break;
            }
        }

        if (found != null) {
            currentInstructor = found;
            if (currentInstructor.getCreatedCourses() == null) {
                currentInstructor.setCreatedCourses(new ArrayList<>());
            }
            return;
        } String newId = UUID.randomUUID().toString();
        currentInstructor = new Instructor(newId, "instructor1", "instructor1@example.com", "", new ArrayList<>());
        jsonUserDb.addUserToFile(currentInstructor);}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboardFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboardFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboardFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboardFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorDashboardFrame1().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsights;
    private javax.swing.JButton btnManageLessons;
    private javax.swing.JButton btnViewEnrolled;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jListCourses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvgScore;
    private javax.swing.JLabel lblCompletion;
    private javax.swing.JLabel lblEnrolled;
    private javax.swing.JPanel pnlInsightsSummary;
    // End of variables declaration//GEN-END:variables
}
